fieldLayouts:
  750a649c-b421-4eb7-9625-5ec5747154c2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: 'Wird auf Website nicht angezeigt.'
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 6720cb60-b2a2-4056-aad9-2f33e3e8f6a5
            instructions: 'Zwei Hochformat-Bilder gleicher Grösse.'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: doppelbild
hasTitleField: true
name: Doppelbild
section: 89b09de4-f600-43e5-a40c-2c1273849092
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
