fieldLayouts:
  692eb8eb-dc66-45a4-b7c9-f986121d230a:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: d1007392-cdf0-4bfe-890d-0e31f5092101
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 🐉
        sortOrder: 1
handle: portfolio
hasTitleField: false
name: Portfolio
section: b4b573d4-09e5-4cef-b829-29055e286a8c
sortOrder: 1
titleFormat: '{section.name|raw}'
