fieldLayouts:
  8fb6421c-2521-46d2-ad79-ae22733ca6e4:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 6720cb60-b2a2-4056-aad9-2f33e3e8f6a5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b31016bc-7398-4a61-a43f-3689e5dc9803
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 🐈
        sortOrder: 1
handle: project
hasTitleField: true
name: Projekt
section: 89b09de4-f600-43e5-a40c-2c1273849092
sortOrder: 1
titleFormat: ''
