contentColumnType: string
fieldGroup: 623e8f21-c10a-45f4-a9bc-6329faaa52bd
handle: mail
instructions: ''
name: 'E-Mail Adresse'
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
