contentColumnType: text
fieldGroup: 623e8f21-c10a-45f4-a9bc-6329faaa52bd
handle: SEO_snippet
instructions: 'Wird von Suchmaschinen erfasst und mit Suchresultat angezeigt.'
name: 'Suchmaschinen Text'
searchable: false
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
