contentColumnType: string
fieldGroup: 11fcf648-c46a-4cb9-bf9c-de04e8ce644a
handle: videos
instructions: ''
name: Video
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:50706d0d-adfc-4561-99a1-bad68c596824'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:50706d0d-adfc-4561-99a1-bad68c596824'
  singleUploadLocationSubpath: 'videos/{slug}'
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
