contentColumnType: text
fieldGroup: 623e8f21-c10a-45f4-a9bc-6329faaa52bd
handle: vimeoId
instructions: 'Vimeo-Code (nicht die ganze URL)'
name: Vimeo-ID
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
