dateModified: 1611773184
email:
  fromEmail: mathias@mathiasrenner.ch
  fromName: 'Mathias Renner'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  sitemap:
    edition: standard
    enabled: true
    schemaVersion: 1.0.2
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Mathias Renner'
  schemaVersion: 3.6.1
  timeZone: Europe/Zurich
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
