enableVersioning: true
handle: portfolio
name: Portfolio
previewTargets:
  -
    label: 'Primäre eintrag Seite'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
    enabledByDefault: true
    hasUrls: true
    template: portfolio
    uriFormat: portfolio
type: single
